# This file is not in use. This project does not use pipefitter
# in circleci, but this was used to locally generate the .circelci/config.yml
# in this directory.
#
# Further modifications were performed after generating the config:
# - removed references to aws-ssm
# - added the `cloudinary` context so it can run integration tests against real cloudinary
ruby-versions: ["supported-versions"]

cache-dependencies: true

pre-test-commands:
  - |
    cd spec/dummy
    bundle install
    bundle exec rails db:migrate RAILS_ENV=test
