source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 7.2'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', require: false
# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'jbuilder'

gem 'sprockets-rails'

gem 'mini_racer'

gem 'cloudinary'
gem 'attachinary-dox', :path => '../..'
gem 'simple_form'
