source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 7.2'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails'
# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'jbuilder', '~> 2.0'

gem 'sprockets-rails'

gem 'cloudinary', '~> 2.3'
gem 'attachinary', :path => '../..'
gem 'simple_form'

